<a href="https://colab.research.google.com/github/claraaqn/Calculo-Numerico/blob/main/Atividade%203%20-%20Sistemas%20Lineares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nome: Maria Clara Aquino Siqueira Souza



## Funções

In [1]:
import numpy as np

In [12]:
def gauss(A, b):
    # A é a matriz dos coeficientes,
    # b é p vetor dos termos independentes

    # tamanho da matriz
    n = len(b)

    # seleciona o pivo
    for k in range(0, n-1):
        if A[k][k] == 0: # verifica se o pivo é 0
            # procura uma linha abaixo para trocar
            for i in range(k+1, n):
                if A[i][k] != 0:
                    # Troca as linhas k e i
                    A[k], A[i] = A[i], A[k]
                    b[k], b[i] = b[i], b[k]
                    det = -det  # troca de linha inverte o sinal do determinante
                    break
                else: # se não encontrou linha para trocar, matriz é singular
                    return A, b, 0  # Ddeterminante zero

        pivo = A[k][k] # vai pegar o número na diagonal

        #precorre as linhas abaixo do pivo para calcular o multiplicador
        for i in range(k+1, n):
            m = A[i][k]/pivo # multiplixador

            # percorre as colunas para fazer a substituição
            for j in range(k, n):
                A[i][j] = A[i][j] - m*A[k][j]

            # atualizando o vetor independete
            b[i] = b[i] - m*b[k]

        # calcula o determinante
        det = 1
        for k in range(n):
            det = det*A[k][k]

    # det é o determinante
    return A, b, det # depois de escalonar

In [3]:
def subs(At, bt):
    n = len(bt)

    # vetor solução inicializados com 0
    x = n*[0]

    # calcula o xn
    x[n-1] = bt[n-1] / At[n-1][n-1]

    # percore as linhas de baixo para cima
    for k in range(n-2, -1,-1):

        # acumula as soluções já disponíveis
        s = 0
        for j in range(k+1, n):
            s = s + At[k][j]*x[j]

        x[k] = (bt[k]-s) / At[k][k]

    # retorna o vetor solução
    return x

In [4]:
def hilbert(n):

    H = [[1/((i+1) + (j+1) - 1) for i in range(n)] for j in range (n)]

    # soma das linhas em H
    b = [sum(row) for row in H]

    # retorna a matriz e o vetor independente
    return H, b

## Teste das funções

In [6]:
# teste para calcular a matriz gaussiana

A = [[3,2,4], [1,1,2], [4,3,-2]]
b = [1,2,3]

At, bt, det_A = gauss(A, b)

print(np.array(At))
print('-'*20)
print(bt)
print('-'*20)
print(det_A)

[[ 3.00000000e+00  2.00000000e+00  4.00000000e+00]
 [ 0.00000000e+00  3.33333333e-01  6.66666667e-01]
 [ 0.00000000e+00  5.55111512e-17 -8.00000000e+00]]
--------------------
[1, 1.6666666666666667, -4.440892098500626e-16]
--------------------
-8.0


In [7]:
# teste para determinar o vetor de solução

x = subs(At, bt)
print(x)

[-3.0, 5.0, 5.551115123125783e-17]


In [8]:
# teste para hilbert

H, bh = hilbert(5)

print(np.array(H))
print('-'*10)
print(bh)

[[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]
----------
[2.283333333333333, 1.45, 1.0928571428571427, 0.8845238095238095, 0.7456349206349207]


## Execução das Matrizes de Hilbert nos n determinados


In [9]:
# para a matriz de hilbert de n=3
n = 3

H_3, b_3 = hilbert(n)

Ht_3, bt_3, det_3 = gauss(H_3, b_3)

x3 = subs(Ht_3, bt_3)

print(det_3)
print('-'*10)
print(x3)

0.00046296296296296005
----------
[0.999999999999998, 1.0000000000000122, 0.9999999999999875]


In [10]:
# para a matriz de hilbert de n=10
n = 10

H_10, b_10 = hilbert(n)

Ht_10, bt_10, det_10 = gauss(H_10, b_10)

x = subs(Ht_10, bt_10)

print(det_10)
print('-'*10)
print(x)

2.164480500135833e-53
----------
[0.9999999987548343, 1.0000001067849729, 0.9999977378614759, 1.0000204794185104, 0.9999026418473482, 1.0002669070133323, 0.99956308847027, 1.0004214011575996, 0.9997791407962119, 1.0000484987218523]


In [11]:
# para a matriz de hilbert de n=100
n = 100

H_100, b_100 = hilbert(n)

Ht_100, bt_100, det_100 = gauss(H_100, b_100)

x = subs(Ht_100, bt_100)

print(det_100)
print('-'*10)
print(x)

0.0
----------
[1.0000000578334154, 1.00000346033331, 0.9993023186253296, 1.0228411217668345, 0.6754244947508906, 3.5050504679527545, -10.56441888079402, 34.39696063912734, -60.724751663427234, 77.65705478942556, -77.08167439284831, 86.19871303939543, -72.49426455043448, 16.549928836019912, 23.958792256252906, -7.319228775776705, 32.21947592380662, -71.51727710716169, -9.468325630904522, 102.14786375496568, -4.398959224546136, -49.22591065029978, -65.42842845668314, 77.29850997064743, 8.937825630063205, 10.739307321918186, -2.8584839567251894, -94.704842845974, 18.509723967222374, 112.92524922991623, 53.29317769377776, -77.717847002712, -45.60028615700258, 0.8527560773744899, -20.409628700566707, -56.15194546538764, 106.6452098429115, -3.4330476211654015, 45.768844521638236, 8.184634619502342, -62.14433983299666, 10.476845168657594, 26.81016976199159, -75.72695047431857, 76.43373944011051, -55.66160624319914, -22.27769000984232, 89.82669695093126, -63.182198099526026, 111.9218607101904

## Conclusão
A medida que vai crescendo o número da Matriz de Hilbert a maquina vai fazendo as divisões das frações e aproximando de maneira errada, então o determinante vai se aproximando do 0 causando a eliminação gaussiana se comportar mal. A máquina vai aproximando de forma errada e isso vai gerando mais e mais erros. Quando fazemos as contas na mão temos a tendência de realizar as operações com as frações, sem resolver as divisões, já a maquina resolve as frações para executar as operações levando ao erro.